apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    cluster.eschercloud.ai/description: "{{ .Values.clusterDescription }}"
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    {{- range $k, $v := .Values.clusterLabels }}
    {{ $k }}: {{ $v }}
    {{- end }}
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ include "resource.default.name" $ }}
  infrastructureRef:
    apiVersion: {{ include "infrastructureApiVersion" . }}
    kind: OpenStackCluster
    name: {{ include "resource.default.name" $ }}
