{{- range .Values.nodePools }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-{{ .name }}-{{- include "kubeAdmConfigTemplateRevision" $ }}
  namespace: {{ $.Release.Namespace }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            {{- include "kubeletExtraArgs" . | nindent  12}}
            node-labels:
              {{- if .nodeLabels }} 
              "eschercloud.ai/node-pool={{ .name }}{{- range $k, $v := .nodeLabels }},{{ $k }}={{ $v }}{{- end }}"
              {{- else }}
              "eschercloud.ai/node-pool={{ .name }}"
              {{- end }}
          name: {{ include "nodeName" . }}
{{- end }}
