{{- if not .Values.cloudConfig }}
{{- $cloud := index .Values.clouds .Values.cloudName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-openstack.cloudCredentialsSecretName" . }}
  labels: {{ include "labels.common" $ | nindent 4 }}
  # If the cloud credentials are deleted before the cluster has finished deleting, then the cluster
  # deletion cannot proceed any further. So prevent Helm from deleting it.
  annotations:
    "helm.sh/resource-policy": keep
stringData:
  # Just include the data for the cloud we will be using
  clouds.yaml: |
    clouds:
      {{ .Values.cloudName | default "openstack" }}:
        {{ index .Values.clouds .Values.cloudName | toYaml | indent 8 | trim }}
  {{- with .Values.cloudCACert }}
  cacert: |
    {{ . | indent 4 | trim }}
  {{- end }}
{{- end }}
